version: '3.4'
services:
    weaviate:
        image: semitechnologies/weaviate:1.24.7
        ports:
            - "8090:8080"
        environment:
            QUERY_DEFAULTS_LIMIT: 25
            AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
            PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
            DEFAULT_VECTORIZER_MODULE: 'none'

    console:
        image: semitechnologies/weaviate-console
        ports:
            - "8081:80"
        environment:
            WEAVIATE__SCHEME: http
            WEAVIATE__HOST: weaviate:8080
        depends_on:
            - weaviate
